### ISSUE TITLE
GKUI 19 APK Installer

### ISSUE THREAD

**Issue by soonychia** [xeon1989/Proton-X50-APK-Installer-GKUI#27]
Dear Chris, 

I follow your step to prepare USB drive up to Step 5, I unplug pendrive from Infotainment system USB port and proceed to step 6 Fill USB drive with APK from PC, my pen drive now like screenshot attached, my pen drive still have APK file after unplug from Infotainment system why still need to "fill in" / copy again? or something wrong somewhere?
[Pendrive.pdf](https://github.com/xeon1989/Proton-X50-APK-Installer-GKUI/files/10763775/Pendrive.pdf)

**Comment by xeon1989** [comment]
Hi, the script installs ES File Explorer for you, which should be done if you completed step 5.
For step 6, you could prepare the additional apps in APK format and place it in USB, so that you can later install those apps in ES File Explorer in step 7 onwards.

**Comment by soonychia** [comment]
Hi Chris, after step 5 installed ES File Explorer, I unplug pendrive and proceed to step 6 - go to PC transfer waze.apk and spotify apk into pendrive then plug it into infotainment again but ES File Explorer straight jump out from screen and no files explored.
https://user-images.githubusercontent.com/125635057/219953450-d56ba9a1-5dca-492a-a581-17a3fc28cdf7.mp4

[USB drive.docx](https://github.com/xeon1989/Proton-X50-APK-Installer-GKUI/files/10777068/USB.drive.docx)

**Comment by xeon1989** [comment]
@soonychia according to the video, it seems ES File explorer crashed. 
Might be the ES file explorer not compatible.

[soonychia.zip](https://github.com/xeon1989/Proton-X50-APK-Installer-GKUI/files/10777468/soonychia.zip)

Could you please unzip above file and place its content in the root of your USB drive below?

![image](https://user-images.githubusercontent.com/17538895/219963046-704abeb4-e39d-4e7f-be92-eb09b993e448.png)

What it does:
- uninstall and delete ES File explore from your IHU
- delete ES.apk from your USB (since it's not compatible)
- install all .apk file in root of your USB drive. 

Note: It might take up to 5 min before you see any changes.

**Comment by soonychia** [comment]
Hi, I have extract soonychia.zip to pen drive and plug to infotainment system but no response after few attempt (screen prompt you want to play photo, video, music, cancel) and I press cancel.
I was wondering why all folder name is the same in Installation script, Uninstallation script and soonychia.zip

**Comment by koperalss** [comment]
> Hi, I have extract soonychia.zip to pen drive and plug to infotainment system but no response after few attempt (screen prompt you want to play photo, video, music, cancel) and I press cancel. I was wondering why all folder name is the same in Installation script, Uninstallation script and soonychia.zip

@soonychia , i think you use the latest ES.apk, it's not compatible, if u hv upgrade to atlas, better use apk installer-atlas

**Comment by soonychia** [comment]
Currently system still is GKUI 19

**Comment by soonychia** [comment]
I did it, thank you so much

I change another USB pen drive and redo the step and ES file doesn't work and I copy the soonychia.zip and it works.

Many thanks for your effort and assistance.
